name: Publish codelab docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - name: Install node modules
        run: npm install
      - name: Install Codelabs command line tool
        run: go get github.com/googlecodelabs/tools/claat
      - name: Publish
        run: ./publish-to-github-pages.sh
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

